package docdb

import (
	"context"
	"fmt"
	"io/ioutil"
	"os"

	tdb "github.com/HouzuoGuo/tiedot/db"
	_ "github.com/go-sql-driver/mysql"
	_ "github.com/mattn/go-sqlite3"
)

type diedotKey int

var key diedotKey = 1

// FromContext
func FromContext(c context.Context) *tdb.DB {
	store, ok := c.Value(key).(*tdb.DB)
	if !ok {
		panic(fmt.Errorf("no db in the app context"))
	}
	return store
}

type Config struct {
	DBDirPath string `yaml:db_path:`
	PersistDB bool   `yaml:persist_database:` // if true, database dir madeby tiedot will not be removed when shutdown.
}

// WithContext graphdb generated by this function waits <- c.Done() so parent context passed to this func as parameter shuld be cancelable and should cancel() called at app will be shutdown.
// database directory will be initiated, create colletions
func WithContext(c context.Context, conf Config) (context.Context, error) {
	return WithContextWithName(c, conf, "", "chaindb", true)
}

func WithContextWithName(c context.Context, conf Config, tempDirPrefix string, dbName string, doInit bool) (context.Context, error) {
	dbDirPath := conf.DBDirPath
	if len(dbDirPath) == 0 {
		var err error
		dbDirPath, err = ioutil.TempDir(tempDirPrefix, dbName)
		if err != nil {
			return c, err
		}
	}

	if fi, err := os.Stat(dbDirPath); os.IsNotExist(err) {
		err := os.MkdirAll(dbDirPath, os.ModeDir)
		if err != nil {
			return c, err
		}
	} else if err != nil {
		return c, err
	} else if !fi.IsDir() {
		return c, fmt.Errorf("%s is not directory", dbDirPath)
	}

	db, err := tdb.OpenDB(dbDirPath)
	if err != nil {
		return c, err
	}

	if doInit {
		err := initDB(db)
		if err != nil {
			return c, err
		}
	}

	c = context.WithValue(c, key, db)

	closeFunc := func() error {
		db.Close()
		os.RemoveAll(dbDirPath)
		return err
	}

	go func() {
		select {
		case <-c.Done():
			closeFunc()
		}
	}()

	return c, nil
}
